name: Publish to Chrome Web Store
on:
    push:
      branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: montudor/action-zip@v1
              with:
                args: zip -qq -r CursorConnect.zip assets customization contentScript.js flip.css flip.js popup.css popup.html popup.js tick.css && zip -j CursorConnect.zip ./platform/chromium/manifest.json
            - uses: mobilefirstllc/cws-publish@latest
              with:
                action: 'upload'
                zip_file: CursorConnect.zip
                extension_id: golmpimdjemjkffedbgjflgbcmcdcfnf
                client_id: ${{ secrets.CLIENT_ID }}
                client_secret: ${{ secrets.CLIENT_SECRET }}
                refresh_token: ${{ secrets.REFRESH_TOKEN }}