name: Publish to Fireffox Add-ons
on:
    push:
      branches: [ "main" ]
    workflow_dispatch:

jobs:
    zip:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: montudor/action-zip@v1
              with:
                args: zip -qq -r CursorConnect.zip assets customization contentScript.js flip.css flip.js popup.css popup.html popup.js tick.css && zip -j CursorConnect.zip ./platform/firefox/manifest.json
            - uses: trmcnvn/firefox-addon@v1
              with:
                uuid: 'cursor@alexinabox.de'
                xpi: CursorConnect.zip
                manifest: /platform/firefox/manifest.json
                api-key: ${{ secrets.FIREFOX_API_KEY }}
                api-secret: ${{ secrets.FIREFOX_API_SECRET }}