name: Publish to Firefox Add-ons
on:
    push:
      branches: [ "main" ]
    workflow_dispatch:

jobs:

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - run: cp platform/firefox/manifest.json manifest.json && rm -rf promo platform
      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: .
          filename: "{name}-{version}.xpi"
          ignoreFiles: '[ "package.json","package-lock.json","yarn.lock" ]'

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: target.xpi
          path: ${{ steps.web-ext-build.outputs.target }}
      
      -name: "Publish"
       uses: actions/checkout@v1
       uses: trmcnvn/firefox-addon@v1
       with:
        uuid: 'cursor@alexinabox.de'
        xpi: ${{ steps.web-ext-build.outputs.target }}
        manifest: platform/firefox/manifest.json
        api-key: ${{ secrets.FIREFOX_API_KEY }}
        api-secret: ${{ secrets.FIREFOX_API_SECRET }}