name: ZipMe
on:
    push:
      branches: [ "dev" ]

jobs:
    zip:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: montudor/action-zip@v1
              with:
                args: zip -qq -r .github/artifacts/CursorConnect.zip assets
            - uses: actions/upload-artifact@v2
              with:
                name: CursorConnect.zip
                path: .github/artifacts/CursorConnect.zip
